version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: techcup
      POSTGRES_USER: tu_usuario
      POSTGRES_PASSWORD: tu_password
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
