# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/techcup}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:tu_usuario}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tu_password}
spring.jpa.hibernate.ddl-auto=update
server.port=8081

# MongoDB
spring.data.mongodb.uri=${SPRING_MONGODB_URI:mongodb://localhost:27017/techcup}

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

security.jwt.secret=bWktY2xhdmUtc3VwZXItc2VjcmV0YS1wYXJhLWp3dC0xMjM0NTY3ODkwMTIzNDU2
