# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/techcup
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=tu_usuario
spring.datasource.password=tu_password
spring.jpa.hibernate.ddl-auto=update

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/techcup

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html